spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/prod?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456     
    
logging:
  config: classpath:log4j2-prod.xml